### ISSUE TITLE
"Bad version number." after update

### ISSUE THREAD

**Issue by statefram** [DiscordInjections/DiscordInjections#65] opened 2017-10-14 00:12 UTC
I've been getting this error ever since discord updated today:
![this](https://my.mixtape.moe/wqlnhv.png)
Most plugins have stopped working, with the exception of custom CSS and the DigitalClock plugin (that i can see)
I've traced it to something with erlpack, since line 43 of DiscordJSBridge is 
`else data = erlpack.unpack(Buffer.from(data));`

**Comment by BoxOfFlex** [comment] 2017-10-14 00:15
Caused by websocket change on Discord's end by the way. Assuming this is more of a d.js webpack issue than DI itself.

**Comment by cking** [comment] 2017-10-19 15:28
Fixed in commit f82109f325555a758a9c8363e3cedb83a46bb826

**Closed by cking** 2017-10-19 15:28 UTC
